import type { PilotRecord } from "./types";

export const PILOT_RECORDS: PilotRecord[] = [
  {
    "id": "US-WMB",
    "ticker": "WMB",
    "name": "The Williams Companies",
    "sector": "Energy",
    "cohort": "US midstream operators",
    "target": true,
    "marketCap": 86.28,
    "ttmRevenue": 12.323,
    "trailingPe": 28.1,
    "evEbitda": 16.62,
    "fcfYield": -0.002,
    "priceBook": 6.56,
    "roic": 0.0795,
    "margin": 0.3814,
    "fyRevenue": 11.83,
    "fyRevenue3": 11.352,
    "note": "Gas-processing and commodity mix; network inventory incomplete."
  },
  {
    "id": "US-KMI",
    "ticker": "KMI",
    "name": "Kinder Morgan",
    "sector": "Energy",
    "cohort": "US midstream operators",
    "target": false,
    "marketCap": 69.19,
    "ttmRevenue": 17.959,
    "trailingPe": 20.04,
    "evEbitda": 13.3,
    "fcfYield": 0.0384,
    "priceBook": 2.19,
    "roic": 0.0624,
    "margin": 0.2905,
    "fyRevenue": 16.937,
    "fyRevenue3": 19.2,
    "note": "Commodity-price revenue exposure; latest EPS outlook is one-sided, no finite guidance midpoint."
  },
  {
    "id": "US-OKE",
    "ticker": "OKE",
    "name": "ONEOK",
    "sector": "Energy",
    "cohort": "US midstream operators",
    "target": false,
    "marketCap": 55.4,
    "ttmRevenue": 39.366,
    "trailingPe": 15.19,
    "evEbitda": 11.51,
    "fcfYield": 0.0525,
    "priceBook": 2.42,
    "roic": 0.0841,
    "margin": 0.1559,
    "fyRevenue": 33.629,
    "fyRevenue3": 22.387,
    "note": "Acquisitions change perimeter; public JV ties documented but inventory incomplete."
  },
  {
    "id": "US-JNJ",
    "ticker": "JNJ",
    "name": "Johnson & Johnson",
    "sector": "Health Care",
    "cohort": "Large-cap pharmaceuticals; JNJ medtech mix",
    "target": true,
    "marketCap": 617.01,
    "ttmRevenue": 97.929,
    "trailingPe": 29.68,
    "evEbitda": 18.5,
    "fcfYield": 0.0361,
    "priceBook": 7.26,
    "roic": 0.1992,
    "margin": 0.2769,
    "fyRevenue": 94.193,
    "fyRevenue3": 79.99,
    "note": "Recast continuing revenue excludes Kenvue. Vendor EPS FY22 6.73 differs from primary continuing GAAP 6.14; EPS diagnostic is vendor-only."
  },
  {
    "id": "US-PFE",
    "ticker": "PFE",
    "name": "Pfizer",
    "sector": "Health Care",
    "cohort": "Large-cap pharmaceuticals; JNJ medtech mix",
    "target": false,
    "marketCap": 158.45,
    "ttmRevenue": 63.696,
    "trailingPe": 36.54,
    "evEbitda": 8.28,
    "fcfYield": 0.0693,
    "priceBook": 1.86,
    "roic": 0.1349,
    "margin": 0.2958,
    "fyRevenue": 62.579,
    "fyRevenue3": 101.175,
    "note": "FY2022 COVID windfall depresses measured subsequent growth; GAAP and adjusted earnings differ."
  },
  {
    "id": "US-MRK",
    "ticker": "MRK",
    "name": "Merck",
    "sector": "Health Care",
    "cohort": "Large-cap pharmaceuticals; JNJ medtech mix",
    "target": false,
    "marketCap": 356.01,
    "ttmRevenue": 66.569,
    "trailingPe": 113.37,
    "evEbitda": 13.95,
    "fcfYield": 0.0451,
    "priceBook": 8.5,
    "roic": 0.1405,
    "margin": 0.3528,
    "fyRevenue": 65.011,
    "fyRevenue3": 59.283,
    "note": "2026 acquisition charges depress trailing EPS; high trailing P/E may not reflect recurring earnings."
  },
  {
    "id": "US-PG",
    "ticker": "PG",
    "name": "Procter & Gamble",
    "sector": "Consumer Staples",
    "cohort": "Household and personal products",
    "target": true,
    "marketCap": 336.58,
    "ttmRevenue": 87.032,
    "trailingPe": 21.88,
    "evEbitda": 14.61,
    "fcfYield": 0.045,
    "priceBook": 6.32,
    "roic": 0.2154,
    "margin": 0.2481,
    "fyRevenue": 87.032,
    "fyRevenue3": 82.006,
    "note": "Vendor margin 24.81% vs primary GAAP 22.6904%; vendor ROIC/margin are proxies. Fiscal June versus peers December."
  },
  {
    "id": "US-CL",
    "ticker": "CL",
    "name": "Colgate-Palmolive",
    "sector": "Consumer Staples",
    "cohort": "Household and personal products",
    "target": false,
    "marketCap": 67.17,
    "ttmRevenue": 21.047,
    "trailingPe": 33.25,
    "evEbitda": 14.76,
    "fcfYield": 0.0574,
    "priceBook": 284.62,
    "roic": 0.4556,
    "margin": 0.2063,
    "fyRevenue": 20.382,
    "fyRevenue3": 17.967,
    "note": "Impairments affect EPS; very small common equity distorts price/book (not scored)."
  },
  {
    "id": "US-CHD",
    "ticker": "CHD",
    "name": "Church & Dwight",
    "sector": "Consumer Staples",
    "cohort": "Household and personal products",
    "target": false,
    "marketCap": 22.37,
    "ttmRevenue": 6.229,
    "trailingPe": 30.29,
    "evEbitda": 18.12,
    "fcfYield": 0.0499,
    "priceBook": 5.14,
    "roic": 0.1401,
    "margin": 0.1809,
    "fyRevenue": 6.203,
    "fyRevenue3": 5.376,
    "note": "FY2022 Flawless impairment depressed EPS base; vendor millions rounded."
  },
  {
    "id": "US-HD",
    "ticker": "HD",
    "name": "The Home Depot",
    "sector": "Consumer Discretionary",
    "cohort": "Home improvement and specialty retail",
    "target": true,
    "marketCap": 282.2,
    "ttmRevenue": 169.176,
    "trailingPe": 19.79,
    "evEbitda": 13.93,
    "fcfYield": 0.0535,
    "priceBook": 16.99,
    "roic": 0.2008,
    "margin": 0.1202,
    "fyRevenue": 164.683,
    "fyRevenue3": 157.403,
    "note": "SRS/GMS acquisitions affect total revenue; FY2022 53 weeks. Issuer fiscal labels corrected from shifted vendor labels."
  },
  {
    "id": "US-LOW",
    "ticker": "LOW",
    "name": "Lowe's Companies",
    "sector": "Consumer Discretionary",
    "cohort": "Home improvement and specialty retail",
    "target": false,
    "marketCap": 101.44,
    "ttmRevenue": 90.432,
    "trailingPe": 15.28,
    "evEbitda": 11.02,
    "fcfYield": 0.069,
    "priceBook": null,
    "roic": 0.2242,
    "margin": 0.1135,
    "fyRevenue": 86.286,
    "fyRevenue3": 97.059,
    "note": "Canada business sale changes scope; FY2022 53 weeks; negative book equity, P/B not scored. Issuer labels corrected."
  },
  {
    "id": "US-TSCO",
    "ticker": "TSCO",
    "name": "Tractor Supply",
    "sector": "Consumer Discretionary",
    "cohort": "Home improvement and specialty retail",
    "target": false,
    "marketCap": 16.2,
    "ttmRevenue": 15.751,
    "trailingPe": 16.2,
    "evEbitda": 11.66,
    "fcfYield": 0.019,
    "priceBook": 6.17,
    "roic": 0.1281,
    "margin": 0.0903,
    "fyRevenue": 15.524,
    "fyRevenue3": 14.205,
    "note": "FY2022 53 weeks. Vendor EPS history is split-adjusted to 5:1 December2024 split."
  },
  {
    "id": "US-ADBE",
    "ticker": "ADBE",
    "name": "Adobe",
    "sector": "Information Technology",
    "cohort": "Application software; business mix differs",
    "target": true,
    "marketCap": 92.51,
    "ttmRevenue": 25.97,
    "trailingPe": 13.27,
    "evEbitda": 9.44,
    "fcfYield": 0.11449999999999999,
    "priceBook": 7.9,
    "roic": 0.5722,
    "margin": 0.3632,
    "fyRevenue": 23.769,
    "fyRevenue3": 17.606,
    "note": "November versus January peer fiscal years; creative/design/CRM product mixes differ."
  },
  {
    "id": "US-CRM",
    "ticker": "CRM",
    "name": "Salesforce",
    "sector": "Information Technology",
    "cohort": "Application software; business mix differs",
    "target": false,
    "marketCap": 193.15,
    "ttmRevenue": 43.938,
    "trailingPe": 21.75,
    "evEbitda": 17.38,
    "fcfYield": 0.0785,
    "priceBook": 5.03,
    "roic": 0.1096,
    "margin": 0.2152,
    "fyRevenue": 41.525,
    "fyRevenue3": 31.352,
    "note": "FY2023 vendor EPS 0.21 creates a tiny-base effect. Informatica acquisition changes perimeter."
  },
  {
    "id": "US-ADSK",
    "ticker": "ADSK",
    "name": "Autodesk",
    "sector": "Information Technology",
    "cohort": "Application software; business mix differs",
    "target": false,
    "marketCap": 44.31,
    "ttmRevenue": 7.79,
    "trailingPe": 27.47,
    "evEbitda": 19.1,
    "fcfYield": 0.0641,
    "priceBook": 13.1,
    "roic": 0.5764,
    "margin": 0.2809,
    "fyRevenue": 7.206,
    "fyRevenue3": 5.005,
    "note": "January fiscal year; architecture/design mix differs from creative and CRM peers."
  },
  {
    "id": "US-VZ",
    "ticker": "VZ",
    "name": "Verizon Communications",
    "sector": "Communication Services",
    "cohort": "US telecom operators; wireless/wireline mix",
    "target": true,
    "marketCap": 190.79,
    "ttmRevenue": 138.895,
    "trailingPe": 11.96,
    "evEbitda": 7.48,
    "fcfYield": 0.11289999999999999,
    "priceBook": 1.84,
    "roic": 0.0827,
    "margin": 0.2307,
    "fyRevenue": 138.191,
    "fyRevenue3": 136.835,
    "note": "Frontier acquisition affects comparability; service-revenue guidance is not total-revenue guidance."
  },
  {
    "id": "US-T",
    "ticker": "T",
    "name": "AT&T",
    "sector": "Communication Services",
    "cohort": "US telecom operators; wireless/wireline mix",
    "target": false,
    "marketCap": 166.51,
    "ttmRevenue": 127.239,
    "trailingPe": 8.01,
    "evEbitda": 7.0,
    "fcfYield": 0.106,
    "priceBook": 1.51,
    "roic": 0.0889,
    "margin": 0.2183,
    "fyRevenue": 125.648,
    "fyRevenue3": 120.741,
    "note": "FY2022 EPS negative: CAGR undefined. DIRECTV divestiture changes perimeter; no fabricated EPS CAGR."
  },
  {
    "id": "US-TMUS",
    "ticker": "TMUS",
    "name": "T-Mobile US",
    "sector": "Communication Services",
    "cohort": "US telecom operators; wireless/wireline mix",
    "target": false,
    "marketCap": 175.53,
    "ttmRevenue": 92.189,
    "trailingPe": 17.16,
    "evEbitda": 8.53,
    "fcfYield": 0.1048,
    "priceBook": 3.13,
    "roic": 0.0893,
    "margin": 0.2209,
    "fyRevenue": 88.309,
    "fyRevenue3": 79.571,
    "note": "Sprint merger/base costs distort EPS history; no annual numeric EPS guidance verified."
  },
  {
    "id": "US-ITW",
    "ticker": "ITW",
    "name": "Illinois Tool Works",
    "sector": "Industrials",
    "cohort": "Industrial machinery; diversified end markets",
    "target": true,
    "marketCap": 74.88,
    "ttmRevenue": 16.469,
    "trailingPe": 23.81,
    "evEbitda": 17.42,
    "fcfYield": 0.039,
    "priceBook": 25.87,
    "roic": 0.2932,
    "margin": 0.2675,
    "fyRevenue": 16.044,
    "fyRevenue3": 15.932,
    "note": "Small diversified-machinery cohort; end-market and divestiture mix differ."
  },
  {
    "id": "US-DOV",
    "ticker": "DOV",
    "name": "Dover",
    "sector": "Industrials",
    "cohort": "Industrial machinery; diversified end markets",
    "target": false,
    "marketCap": 25.55,
    "ttmRevenue": 8.421,
    "trailingPe": 22.93,
    "evEbitda": 14.17,
    "fcfYield": 0.045899999999999996,
    "priceBook": 3.32,
    "roic": 0.1321,
    "margin": 0.1802,
    "fyRevenue": 8.093,
    "fyRevenue3": 7.844,
    "note": "Disposals change perimeter; vendor GAAP EPS is separate from restated management adjusted continuing EPS."
  },
  {
    "id": "US-IR",
    "ticker": "IR",
    "name": "Ingersoll Rand",
    "sector": "Industrials",
    "cohort": "Industrial machinery; diversified end markets",
    "target": false,
    "marketCap": 29.52,
    "ttmRevenue": 7.942,
    "trailingPe": 31.28,
    "evEbitda": 16.5,
    "fcfYield": 0.041299999999999996,
    "priceBook": 2.9,
    "roic": 0.0847,
    "margin": 0.1863,
    "fyRevenue": 7.651,
    "fyRevenue3": 5.916,
    "note": "Acquisitions affect growth. Vendor FY2022 EPS 1.48 differs from primary 1.47."
  },
  {
    "id": "US-SHW",
    "ticker": "SHW",
    "name": "Sherwin-Williams",
    "sector": "Materials",
    "cohort": "Specialty chemicals; coatings/water/hygiene mix",
    "target": true,
    "marketCap": 77.11,
    "ttmRevenue": 24.41,
    "trailingPe": 29.47,
    "evEbitda": 19.5,
    "fcfYield": 0.0417,
    "priceBook": 20.0,
    "roic": 0.1639,
    "margin": 0.1632,
    "fyRevenue": 23.574,
    "fyRevenue3": 22.149,
    "note": "Broad specialty-chemicals cohort with coatings/water/hygiene differences; vendor margin 16.32% versus financials 16.31% rounding."
  },
  {
    "id": "US-PPG",
    "ticker": "PPG",
    "name": "PPG Industries",
    "sector": "Materials",
    "cohort": "Specialty chemicals; coatings/water/hygiene mix",
    "target": false,
    "marketCap": 23.37,
    "ttmRevenue": 16.421,
    "trailingPe": 15.09,
    "evEbitda": 10.81,
    "fcfYield": 0.0602,
    "priceBook": 2.77,
    "roic": 0.1163,
    "margin": 0.1315,
    "fyRevenue": 15.875,
    "fyRevenue3": 15.614,
    "note": "Vendor net-income EPS differs from adjusted continuing EPS; coatings divestitures change historical perimeter."
  },
  {
    "id": "US-ECL",
    "ticker": "ECL",
    "name": "Ecolab",
    "sector": "Materials",
    "cohort": "Specialty chemicals; coatings/water/hygiene mix",
    "target": false,
    "marketCap": 76.73,
    "ttmRevenue": 16.843,
    "trailingPe": 36.72,
    "evEbitda": 20.68,
    "fcfYield": 0.024399999999999998,
    "priceBook": 7.63,
    "roic": 0.1338,
    "margin": 0.1844,
    "fyRevenue": 16.081,
    "fyRevenue3": 14.188,
    "note": "Water/hygiene versus coatings peer mix; not a pure coatings comparison."
  },
  {
    "id": "US-AEP",
    "ticker": "AEP",
    "name": "American Electric Power",
    "sector": "Utilities",
    "cohort": "US regulated electric utilities",
    "target": true,
    "marketCap": 65.09,
    "ttmRevenue": 22.791,
    "trailingPe": 20.71,
    "evEbitda": 13.07,
    "fcfYield": -0.09050000000000001,
    "priceBook": 2.03,
    "roic": 0.0416,
    "margin": 0.2398,
    "fyRevenue": 21.876,
    "fyRevenue3": 19.64,
    "note": "Vendor ROIC and margin do not reproduce the approved operating-tax/average-capital equation. Negative FCF retained but not weighted in utility value."
  },
  {
    "id": "US-DUK",
    "ticker": "DUK",
    "name": "Duke Energy",
    "sector": "Utilities",
    "cohort": "US regulated electric utilities",
    "target": false,
    "marketCap": 88.99,
    "ttmRevenue": 32.803,
    "trailingPe": 17.18,
    "evEbitda": 10.86,
    "fcfYield": -0.048,
    "priceBook": 1.66,
    "roic": 0.0383,
    "margin": 0.2704,
    "fyRevenue": 31.79,
    "fyRevenue3": 28.319,
    "note": "Vendor revenue differs from consolidated reported revenue (TTM 32.803 vs33.250bn). Disposals affect EPS. Utility book-value profile."
  },
  {
    "id": "US-XEL",
    "ticker": "XEL",
    "name": "Xcel Energy",
    "sector": "Utilities",
    "cohort": "US regulated electric utilities",
    "target": false,
    "marketCap": 44.6,
    "ttmRevenue": 14.616,
    "trailingPe": 19.58,
    "evEbitda": 13.76,
    "fcfYield": -0.1725,
    "priceBook": 1.85,
    "roic": 0.032,
    "margin": 0.2103,
    "fyRevenue": 14.669,
    "fyRevenue3": 15.31,
    "note": "Vendor operating income differs from reported GAAP. Negative FCF retained but not scored in utility profile."
  },
  {
    "id": "US-PYPL",
    "ticker": "PYPL",
    "name": "PayPal Holdings",
    "sector": "Financials",
    "cohort": "Transaction and payment processing services",
    "target": true,
    "marketCap": 45.17,
    "ttmRevenue": 34.128,
    "trailingPe": 9.95,
    "evEbitda": 7.46,
    "fcfYield": 0.1458,
    "priceBook": 2.3,
    "roic": 0.2227,
    "margin": 0.1761,
    "fyRevenue": 33.172,
    "fyRevenue3": 27.518,
    "note": "Processor/merchant mix versus Visa/Mastercard payment networks; margin differences are structural."
  },
  {
    "id": "US-MA",
    "ticker": "MA",
    "name": "Mastercard",
    "sector": "Financials",
    "cohort": "Transaction and payment processing services",
    "target": false,
    "marketCap": 483.79,
    "ttmRevenue": 35.083,
    "trailingPe": 30.37,
    "evEbitda": 22.37,
    "fcfYield": 0.0345,
    "priceBook": 86.34,
    "roic": 0.9378,
    "margin": 0.5988,
    "fyRevenue": 32.791,
    "fyRevenue3": 22.237,
    "note": "Payment-network model versus PayPal processor; annual fiscal December."
  },
  {
    "id": "US-V",
    "ticker": "V",
    "name": "Visa",
    "sector": "Financials",
    "cohort": "Transaction and payment processing services",
    "target": false,
    "marketCap": 662.03,
    "ttmRevenue": 44.488,
    "trailingPe": 30.7,
    "evEbitda": 21.61,
    "fcfYield": 0.0317,
    "priceBook": 19.11,
    "roic": 0.5482,
    "margin": 0.6688,
    "fyRevenue": 40.0,
    "fyRevenue3": 29.31,
    "note": "September fiscal year versus December peers; payment-network model versus processor."
  }
];
